### ISSUE TITLE
Dequantization

### ISSUE THREAD

**Issue by ebsrn** [linyang-zhh/FQ-ViT#6]
Hi, thank you for sharing the coding.

Could you please explain why you dequantize the values after quantization?

https://github.com/linyang-zhh/FQ-ViT/blob/16122ee7ea33e80aed3edd29cfebb3ab2ce2cb69/models/ptq/quantizer/base.py#L46

**Comment by linyang-zhh** [comment]
@ebsrn 
Hi! In order to ensure the flexibility of future work (e.g. supporting training or fine-tuning), we use FakeQuantization. More information can be found in this [link](https://pytorch.org/docs/stable/quantization.html) and this [paper](http://arxiv.org/abs/1712.05877).

**Comment by ebsrn** [comment]
Thank you.

**Comment by ebsrn** [comment]
Hi again,
I'm trying to do the inference with quantized weights. For this, I deleted the following line. Is this a correct approach? When I do this, I see that the output of the layer before the classification layer consists entirely of nan values. 

https://github.com/linyang-zhh/FQ-ViT/blob/16122ee7ea33e80aed3edd29cfebb3ab2ce2cb69/models/ptq/quantizer/base.py#L46

**Comment by linyang-zhh** [comment]
@ebsrn Hi,
`quant` and `dequant` are the standard and necessary steps in quantization and you can't remove any of them.
These steps are introduced in the above-mentioned documents, and Figure. 6 in [this paper](http://arxiv.org/abs/2103.13630). I hope you could read these articles carefully, in order to enhance the understanding of quantization.
